# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: ${APP_PORT:8080}
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    org.springframework: warn

# Spring配置
spring:
  # 应用名称
  application:
    name: ${APP_NAME:mapgis-xxx-server}
  profiles:
    # 环境配置
    active: dev
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size: 10MB
      # 设置总上传的文件大小
      max-request-size: 20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:
    pathmatch:
      # 适配 boot 2.6 路由与 springfox 兼容
      matching-strategy: ant_path_matcher
  # 缓存配置
  cache:
    type: ehcache
    ehcache:
      config: classpath:ehcache.xml

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.zondy.mapgis.**.domain
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 标题
  title: ${SWAGGER_DOC_TIILE:MapGIS服务器产品 接口文档}
  # 描述
  description: ${SWAGGER_DOC_DESC:MapGIS服务器产品}
  version: @mapgis.boot.version@

# 安全配置
security:
  # 验证码
  captcha:
    enabled: true
    # 验证码类型 math 数组计算 char 字符验证
    type: math
  # 防止XSS攻击
  xss:
    # 过滤开关
    enabled: true
    # 排除链接（多个用逗号分隔）
    excludes: /xxx/rest/manager/system/notice
    # 匹配链接（多个用逗号分隔）
    urlPatterns: /xxx/rest/manager/system/*,/xxx/rest/manager/monitor/*,/xxx/rest/manager/tool/*
  # 访问
  access:
    # 只读开关
    readonlyEnabled: ${SECURITY_ACCESS_READONLYENABLED:false}

# API前缀
api:
  path:
    services-prefix: xxx/rest/services
    manager-prefix: xxx/rest/manager

# 本地文件上传
file:
  path: /upload
  prefix: /profile

# FastDFS配置
fdfs:
  domain: http://127.0.0.1
  soTimeout: 3000
  connectTimeout: 2000
  trackerList: 127.0.0.1:22122

# Minio配置
minio:
  url: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: test